"""empty message

Revision ID: 740524d8db37
Revises: 9a64fc339b4e
Create Date: 2021-07-28 10:06:24.170502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740524d8db37'
down_revision = '9a64fc339b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('last_name', sa.String(length=140), nullable=True))
    op.add_column('book', sa.Column('phone', sa.String(length=140), nullable=True))
    op.drop_column('book', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('number', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('book', 'phone')
    op.drop_column('book', 'last_name')
    # ### end Alembic commands ###
