"""empty message

Revision ID: 9a64fc339b4e
Revises: e157c9ea1030
Create Date: 2021-07-27 09:16:15.283606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a64fc339b4e'
down_revision = 'e157c9ea1030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('name', sa.String(length=140), nullable=True))
    op.add_column('book', sa.Column('number', sa.String(length=140), nullable=True))
    op.drop_column('book', 'person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('person', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('book', 'number')
    op.drop_column('book', 'name')
    # ### end Alembic commands ###
